import {
  NodeTypeString,
  NodeConfig,
  BeginNodeData,
  InterfaceNodeData,
  GenerateNodeData,
  CategorizeNodeData,
  RetrievalNodeData,
  DecisionNodeData,
  KeywordsNodeData,
  ExecMysqlNodeData,
  ExecMssqlNodeData,
  SubAgentNodeData,
  AgentNodeData,
  SendMailNodeData,
  GoogleSearchNodeData,
  BingSearchNodeData,
  DuckGoSearchNodeData,
  WikipediaSearchNodeData,
  RewriteNodeData,
  HttpRequestNodeData,
  TransformNodeData,
  FileReadNodeData,
  FileWriteNodeData,
  DelayNodeData,
  WebhookNodeData,
  TextProcessNodeData,
  JsonParseNodeData,
  ValidateNodeData,
  MathNodeData,
  DateTimeNodeData,
  ConditionNodeData,
  MattermostNodeData,
  SlackNodeData,
  JiraNodeData,
  GitLabNodeData,
  ConfluenceNodeData,
  GitHubNodeData,
  FacebookNodeData,
  GoogleMapNodeData,
  TwitterNodeData,
  InstagramNodeData,
  LinkedInNodeData,
  YouTubeNodeData,
  TikTokNodeData,
  DiscordNodeData,
  TelegramNodeData,
  WhatsAppNodeData,
  WeatherNodeData,
  DisplayNodeData,
  LoopNodeData,
  VariableNodeData,
  CodeNodeData,
  TemplateNodeData,
  CounterNodeData,
  CacheNodeData,
  LogNodeData,
  FileAnalysisNodeData,
  CsvAnalysisNodeData,
  ImageAnalysisNodeData,
  PdfAnalysisNodeData,
  LogAnalysisNodeData,
  ExcelAnalysisNodeData,
  WeChatNodeData,
  ExecPostgresNodeData,
} from '../../models/flowTypes';
import {
  BranchesOutlined,
  DatabaseOutlined,
  PlayCircleOutlined,
  QuestionOutlined,
  RobotOutlined,
  SendOutlined,
  TagsOutlined,
  TeamOutlined,
  MailOutlined,
  SearchOutlined,
  GlobalOutlined,
  EditOutlined,
  ApiOutlined,
  SwapOutlined,
  FileTextOutlined,
  SaveOutlined,
  ClockCircleOutlined,
  LinkOutlined,
  CodeOutlined,
  FontSizeOutlined,
  CheckCircleOutlined,
  CalculatorOutlined,
  FieldTimeOutlined,
  BranchesOutlined as ConditionOutlined,
  MessageOutlined,
  SlackOutlined,
  GitlabOutlined,
  GithubOutlined,
  FacebookOutlined,
  EnvironmentOutlined,
  TwitterOutlined,
  InstagramOutlined,
  LinkedinOutlined,
  YoutubeOutlined,
  CustomerServiceOutlined,
  RobotOutlined as DiscordIcon,
  PhoneOutlined,
  WhatsAppOutlined,
  CloudOutlined,
  EyeOutlined,
  ReloadOutlined,
  SettingOutlined,
  CodeOutlined as CodeIcon,
  FileTextOutlined as TemplateIcon,
  NumberOutlined,
  InboxOutlined,
  FileSearchOutlined,
  TableOutlined,
  PictureOutlined,
  FilePdfOutlined,
  BugOutlined,
  FileExcelOutlined,
  WechatOutlined,
  ApartmentOutlined,
} from '@ant-design/icons';

// Central registry of all node types
export const NODE_REGISTRY: Record<NodeTypeString, NodeConfig> = {
  begin: {
    type: 'begin',
    icon: <PlayCircleOutlined />,

    input: 'None',
    output: 'Initial variables and greeting message',
    data: {
      type: 'begin',
      form: {
        role: 'system',
        name: 'Begin',
        greeting: 'Hello!',
        variables: [],
        description: 'Starting point of the flow',
        output: '', // Required by BaseForm
      },
    } as Partial<BeginNodeData>,
  },

  interface: {
    type: 'interface',
    icon: <SendOutlined />,
    input: 'Previous node output or user input',
    output: 'User input for next node',
    data: {
      name: 'Interface',
      type: 'interface',
      form: {
        role: 'developer',
        name: 'Interface',
        displayFormat: 'text',
        output: '', // Required by BaseForm
      },
    } as Partial<InterfaceNodeData>,
  },

  generate: {
    type: 'generate',
    icon: <RobotOutlined />,
    input: 'Prompt template with variables',
    output: 'AI-generated content',
    data: {
      type: 'generate',
      form: {
        name: 'Generate',
        role: 'assistant',
        description: 'Generate content using AI',
        prompt: `Role: Be a helpful assistant.
- Additional knowledge: @`,
        model: '',
        outputVariable: 'generatedText',
        output: '', // Required by BaseForm
        numberHistory: 8, // Default to 8, can be set by user
      },
    } as Partial<GenerateNodeData>,
  },

  categorize: {
    type: 'categorize',
    icon: <BranchesOutlined />,
    input: 'Text to categorize',
    output: 'Categorized output',

    data: {
      type: 'categorize',
      form: {
        role: 'developer',
        name: 'Categorize',

        model: '',

        description: 'Categorize input into different paths',
        categories: [
          {
            name: 'positive',
            description: 'Positive sentiment or feedback',
            examples: ['I love this product', 'Great service', 'Works perfectly'],
          },
          {
            name: 'negative',
            description: 'Negative sentiment or feedback',
            examples: ['Not working', 'Poor quality', 'Very disappointing'],
          },
        ],
        defaultCategory: 'positive',
        inputRefs: [], // Add this to initialize the input references array
        output: '', // Required by BaseForm
      },
    } as Partial<CategorizeNodeData>,
  },
  retrieval: {
    type: 'retrieval',
    icon: <DatabaseOutlined />,
    input: 'Query text for search',
    output: 'Retrieved information from knowledge bases',
    data: {
      type: 'retrieval',
      form: {
        name: 'Retrieval',
        role: 'developer',
        description: 'Retrieve information from knowledge base',
        knowledgeIds: [],
        maxResults: 15,
        threshold: 0.7,
        inputRefs: [], // Only retrieval node needs this initialized
      },
    } as Partial<RetrievalNodeData>,
  },
  decision: {
    type: 'decision',
    icon: <QuestionOutlined />,
    input: 'Variables from previous nodes',
    output: 'Path based on condition groups',
    data: {
      type: 'decision',

      form: {
        name: 'Decision',
        description: 'Route flow based on conditional logic',
        role: 'developer',
        branches: [
          {
            name: 'Branch 1',
            groups: [
              {
                conditions: [{ input: '', operator: 'equals', value: '' }],
                logicalOperator: 'AND',
              },
            ],
            groupOperator: 'OR',
            targetNode: '',
          },
        ],
        defaultTarget: '',
        inputRefs: [],
      },
    } as Partial<DecisionNodeData>,
  },
  keywords: {
    type: 'keywords',
    icon: <TagsOutlined />,
    input: 'Text to extract keywords from',
    output: 'Extracted keywords',
    data: {
      type: 'keywords',
      form: {
        role: 'developer',
        name: 'Keywords',
        description: 'Extract keywords from input text',
        model: '',
        prompt: `Extract keywords from conversation:
        The conversation below is between a user and an AI assistant.
        {{conversation}}
        {{extraInfo}}
        Extract the most relevant keywords from the conversation above.
        Keywords should be separated by commas.`,
        maxResults: 10,
        inputRefs: [],
        output: '',
        numberHistory: 8, // Default to 8, can be set by user
      },
    } as Partial<KeywordsNodeData>,
  },
  nativekeywords: {
    type: 'nativekeywords',
    icon: <TagsOutlined />,
    input: 'Raw text or variables to extract from',
    output: 'Keywords (comma-separated or JSON array)',
    data: {
      type: 'nativekeywords',
      form: {
        role: 'developer',
        name: 'Local Keywords',
        description: 'Extract keywords locally without AI',
        text: '${conversation}',
        language: 'auto',
        maxResults: 10,
        minLength: 3,
        removeDigits: true,
        extraStopwords: [],
        inputRefs: [],
        output: '',
      },
    },
  },
  execmysql: {
    type: 'execmysql',
    icon: <DatabaseOutlined />,
    input: 'Variables for SQL query substitution',
    output: 'Query results as JSON array',
    data: {
      type: 'execmysql',
      form: {
        role: 'developer',
        name: 'MySQL Execution',
        description: 'Execute MySQL queries and return results',
        query: 'SELECT * FROM table_name LIMIT 10',
        server: 'localhost',
        port: 3306,
        user: '',
        password: '',
        database: '',
        timeout: 30,
        maxRows: 100,
        inputRefs: [],
        output: '',
      },
    } as Partial<ExecMysqlNodeData>,
  },
  execmssql: {
    type: 'execmssql',
    icon: <DatabaseOutlined />,

    input: 'Variables for SQL query substitution',
    output: 'Query results as JSON array',
    data: {
      type: 'execmssql',
      form: {
        role: 'developer',
        name: 'MSSQL Execution',
        description: 'Execute Microsoft SQL Server queries and return results',
        query: 'SELECT * FROM table_name',
        server: 'localhost',
        port: 1433,
        user: '',
        password: '',
        database: '',
        timeout: 30,
        maxRows: 100,
        trustServerCertificate: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<ExecMssqlNodeData>,
  },
  execpostgres: {
    type: 'execpostgres',
    icon: <DatabaseOutlined />,
    input: 'Variables for SQL query substitution',
    output: 'Query results as JSON array',
    data: {
      type: 'execpostgres',
      form: {
        role: 'developer',
        name: 'PostgreSQL Execution',
        description: 'Execute PostgreSQL queries and return results',
        query: 'SELECT * FROM table_name LIMIT 10',
        server: 'localhost',
        port: 5432,
        user: '',
        password: '',
        database: '',
        timeout: 30,
        maxRows: 100,
        ssl: false,
        inputRefs: [],
        output: '',
      },
    } as Partial<ExecPostgresNodeData>,
  },
  subagent: {
    type: 'subagent',
    icon: <TeamOutlined />,
    input: 'Variables and context from current flow',
    output: 'Results from sub-agent execution',
    data: {
      type: 'subagent',
      form: {
        role: 'developer',
        name: 'Sub Agent',
        description: 'Execute another agent/flow as a sub-process',
        agentId: '',
        agentName: '',
        variables: {},
        timeout: 300,
        inheritContext: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<SubAgentNodeData>,
  },
  agent: {
    type: 'agent',
    icon: <ApartmentOutlined />,
    input: 'User request or data to be processed',
    output: "Result from the agent's execution or delegated task",
    data: {
      type: 'agent',
      form: {
        role: 'developer',
        name: 'Agent',
        description: 'Acts as a central coordinator that can execute tools and delegate tasks to other agents.',
        systemMessage:
          'You are a helpful assistant. Your role is to analyze the user input and decide which tool or other agent to use to best answer the request.',
        inputRefs: [],
        output: '',
      },
    } as Partial<AgentNodeData>,
  },
  sendmail: {
    type: 'sendmail',
    icon: <MailOutlined />,
    input: 'Email content and recipient information',
    output: 'Email sending status and result',
    data: {
      type: 'sendmail',
      form: {
        role: 'developer',
        name: 'Send Mail',
        description: 'Send emails with dynamic content',
        to: '',
        subject: 'Notification from Flow',
        body: 'Hello,\n\nThis is an automated message from your flow.\n\nBest regards',
        isHtml: false,
        useSystemConfig: true,
        smtpHost: 'smtp.gmail.com',
        smtpPort: 587,
        smtpUser: '',
        smtpPassword: '',
        smtpSecure: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<SendMailNodeData>,
  },
  googlesearch: {
    type: 'googlesearch',
    icon: <SearchOutlined />,

    input: 'Search query text',
    output: 'Search results with titles, descriptions, and URLs',
    data: {
      type: 'googlesearch',
      form: {
        role: 'developer',
        name: 'Google Search',
        description: 'Search Google for information and return results',
        query: '{{searchTerm}}',
        maxResults: 10,
        safeSearch: 'moderate',
        language: 'en',
        country: 'us',
        useSystemConfig: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<GoogleSearchNodeData>,
  },
  wikipediasearch: {
    type: 'wikipediasearch',
    icon: <GlobalOutlined />,

    input: 'Search query text',
    output: 'Wikipedia articles with summaries and URLs',
    data: {
      type: 'wikipediasearch',
      form: {
        role: 'developer',
        name: 'Wikipedia Search',
        description: 'Search Wikipedia for information and return articles',
        query: '{{searchTerm}}',
        maxResults: 5,
        language: 'en',
        summaryOnly: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<WikipediaSearchNodeData>,
  },
  rewrite: {
    type: 'rewrite',
    icon: <EditOutlined />,

    input: 'Text and conversation history to rewrite',
    output: 'Rewritten and improved text',
    data: {
      type: 'rewrite',
      form: {
        role: 'assistant',
        name: 'Rewrite',
        description: 'Rewrite and improve questions from conversation history',
        model: '',
        prompt: `Based on the conversation history, rewrite the user's latest question to be more complete, clear, and contextually aware.

Conversation history:
{{conversation}}

Current question: {{userInput}}

Instructions:
- Make the question self-contained and complete
- Include relevant context from the conversation
- Maintain the original intent and meaning
- Make it more specific and actionable
- Use professional language

Rewritten question:`,
        numberHistory: 5,
        preserveMeaning: true,
        outputStyle: 'professional',
        inputRefs: [],
        output: '',
      },
    } as Partial<RewriteNodeData>,
  },
  httprequest: {
    type: 'httprequest',
    icon: <ApiOutlined />,
    input: 'URL parameters and request data',
    output: 'HTTP response data',
    data: {
      type: 'httprequest',
      form: {
        role: 'developer',
        name: 'HTTP Request',
        description: 'Make HTTP requests to external APIs',
        method: 'GET',
        url: 'https://api.example.com/{{endpoint}}',
        timeout: 30,
        followRedirects: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<HttpRequestNodeData>,
  },
  transform: {
    type: 'transform',
    icon: <SwapOutlined />,

    input: 'Data to transform',
    output: 'Transformed data',
    data: {
      type: 'transform',
      form: {
        role: 'developer',
        name: 'Transform',
        description: 'Transform and manipulate data',
        transformType: 'json',
        transformation: 'data.map(item => ({ ...item, processed: true }))',
        inputData: '{{previousNodeOutput}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<TransformNodeData>,
  },
  fileread: {
    type: 'fileread',
    icon: <FileTextOutlined />,
    input: 'File path to read',
    output: 'File content',
    data: {
      type: 'fileread',
      form: {
        role: 'developer',
        name: 'File Read',
        description: 'Read content from files',
        filePath: '/path/to/file.txt',
        encoding: 'utf8',
        maxSize: 1048576, // 1MB
        inputRefs: [],
        output: '',
      },
    } as Partial<FileReadNodeData>,
  },
  filewrite: {
    type: 'filewrite',
    icon: <SaveOutlined />,

    input: 'Content to write to file',
    output: 'Write operation result',
    data: {
      type: 'filewrite',
      form: {
        role: 'developer',
        name: 'File Write',
        description: 'Write content to files',
        filePath: '/path/to/output.txt',
        content: '{{contentToWrite}}',
        encoding: 'utf8',
        overwrite: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<FileWriteNodeData>,
  },
  delay: {
    type: 'delay',
    icon: <ClockCircleOutlined />,

    input: 'Previous node output',
    output: 'Same as input after delay',
    data: {
      type: 'delay',
      form: {
        role: 'developer',
        name: 'Delay',
        description: 'Add a delay in flow execution',
        duration: 5,
        unit: 'seconds',
        inputRefs: [],
        output: '',
      },
    } as Partial<DelayNodeData>,
  },
  webhook: {
    type: 'webhook',
    icon: <LinkOutlined />,

    input: 'Data to send via webhook',
    output: 'Webhook response',
    data: {
      type: 'webhook',
      form: {
        role: 'developer',
        name: 'Webhook',
        description: 'Send data to webhook endpoints',
        webhookUrl: 'https://hooks.example.com/webhook',
        method: 'POST',
        payload: '{{dataToSend}}',
        retryCount: 3,
        inputRefs: [],
        output: '',
      },
    } as Partial<WebhookNodeData>,
  },
  jsonparse: {
    type: 'jsonparse',
    icon: <CodeOutlined />,

    input: 'JSON data to parse or manipulate',
    output: 'Processed JSON result',
    data: {
      type: 'jsonparse',
      form: {
        role: 'developer',
        name: 'JSON Parse',
        description: 'Parse, stringify, or extract data from JSON',
        jsonData: '{{inputData}}',
        operation: 'parse',
        outputFormat: 'object',
        inputRefs: [],
        output: '',
      },
    } as Partial<JsonParseNodeData>,
  },
  textprocess: {
    type: 'textprocess',
    icon: <FontSizeOutlined />,

    input: 'Text to process',
    output: 'Processed text result',
    data: {
      type: 'textprocess',
      form: {
        role: 'developer',
        name: 'Text Process',
        description: 'Process and manipulate text strings',
        inputText: '{{textInput}}',
        operation: 'trim',
        inputRefs: [],
        output: '',
      },
    } as Partial<TextProcessNodeData>,
  },
  validate: {
    type: 'validate',
    icon: <CheckCircleOutlined />,
   
    input: 'Data to validate',
    output: 'Validation result (true/false)',
    data: {
      type: 'validate',
      form: {
        role: 'developer',
        name: 'Validate',
        description: 'Validate data format and constraints',
        inputData: '{{dataToValidate}}',
        validationType: 'email',
        required: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<ValidateNodeData>,
  },
  math: {
    type: 'math',
    icon: <CalculatorOutlined />,
    input: 'Numbers for mathematical operations',
    output: 'Calculation result',
    data: {
      type: 'math',
      form: {
        role: 'developer',
        name: 'Math',
        description: 'Perform mathematical calculations',
        operation: 'add',
        value1: '{{number1}}',
        value2: '{{number2}}',
        precision: 2,
        inputRefs: [],
        output: '',
      },
    } as Partial<MathNodeData>,
  },
  datetime: {
    type: 'datetime',
    icon: <FieldTimeOutlined />,
    input: 'Date/time data to process',
    output: 'Processed date/time result',
    data: {
      type: 'datetime',
      form: {
        role: 'developer',
        name: 'Date Time',
        description: 'Process and manipulate dates and times',
        operation: 'now',
        format: 'YYYY-MM-DD HH:mm:ss',
        inputRefs: [],
        output: '',
      },
    } as Partial<DateTimeNodeData>,
  },
  condition: {
    type: 'condition',
    icon: <ConditionOutlined />,
    input: 'Values to compare',
    output: 'Conditional result based on comparison',
    data: {
      type: 'condition',
      form: {
        role: 'developer',
        name: 'Condition',
        description: 'Compare values and return result based on condition',
        leftValue: '{{value1}}',
        operator: 'equals',
        rightValue: '{{value2}}',
        trueValue: 'Success',
        falseValue: 'Failed',
        dataType: 'string',
        inputRefs: [],
        output: '',
      },
    } as Partial<ConditionNodeData>,
  },
  mattermost: {
    type: 'mattermost',
    icon: <MessageOutlined />,
    input: 'Message content and channel information',
    output: 'Mattermost operation result',
    data: {
      type: 'mattermost',
      form: {
        role: 'developer',
        name: 'Mattermost',
        description: 'Interact with Mattermost for team communication',
        action: 'send_message',
        serverUrl: 'https://your-mattermost.com',
        accessToken: '',
        message: '{{messageContent}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<MattermostNodeData>,
  },
  slack: {
    type: 'slack',
    icon: <SlackOutlined />,
    input: 'Message content and channel information',
    output: 'Slack operation result',
    data: {
      type: 'slack',
      form: {
        role: 'developer',
        name: 'Slack',
        description: 'Interact with Slack for team communication',
        action: 'send_message',
        botToken: '',
        message: '{{messageContent}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<SlackNodeData>,
  },
  jira: {
    type: 'jira',
    icon: <BugOutlined />,
    input: 'Issue details and project information',
    output: 'Jira operation result',
    data: {
      type: 'jira',
      form: {
        role: 'developer',
        name: 'Jira',
        description: 'Interact with Jira for issue management',
        action: 'create_issue',
        serverUrl: 'https://your-domain.atlassian.net',
        username: '',
        apiToken: '',
        summary: '{{issueTitle}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<JiraNodeData>,
  },
  gitlab: {
    type: 'gitlab',
    icon: <GitlabOutlined />,
    input: 'Project details and operation data',
    output: 'GitLab operation result',
    data: {
      type: 'gitlab',
      form: {
        role: 'developer',
        name: 'GitLab',
        description: 'Interact with GitLab for project management',
        action: 'create_issue',
        serverUrl: 'https://gitlab.com',
        accessToken: '',
        title: '{{issueTitle}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<GitLabNodeData>,
  },
  confluence: {
    type: 'confluence',
    icon: <FileTextOutlined />,
    input: 'Page content and space information',
    output: 'Confluence operation result',
    data: {
      type: 'confluence',
      form: {
        role: 'developer',
        name: 'Confluence',
        description: 'Interact with Confluence for content management',
        action: 'create_page',
        serverUrl: 'https://your-domain.atlassian.net',
        username: '',
        apiToken: '',
        title: '{{pageTitle}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<ConfluenceNodeData>,
  },
  github: {
    type: 'github',
    icon: <GithubOutlined />,
    input: 'Repository details and operation data',
    output: 'GitHub operation result',
    data: {
      type: 'github',
      form: {
        role: 'developer',
        name: 'GitHub',
        description: 'Interact with GitHub for repository and project management',
        action: 'create_issue',
        token: '',
        owner: '',
        repository: '',
        title: '{{issueTitle}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<GitHubNodeData>,
  },
  facebook: {
    type: 'facebook',
    icon: <FacebookOutlined />,
    input: 'Post content and page information',
    output: 'Facebook operation result',
    data: {
      type: 'facebook',
      form: {
        role: 'developer',
        name: 'Facebook',
        description: 'Interact with Facebook for social media management',
        action: 'create_post',
        accessToken: '',
        message: '{{postContent}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<FacebookNodeData>,
  },
  googlemap: {
    type: 'googlemap',
    icon: <EnvironmentOutlined />,
    input: 'Location data and search parameters',
    output: 'Google Maps API result',
    data: {
      type: 'googlemap',
      form: {
        role: 'developer',
        name: 'Google Map',
        description: 'Interact with Google Maps for location services',
        action: 'geocode',
        apiKey: '',
        address: '{{locationQuery}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<GoogleMapNodeData>,
  },
  twitter: {
    type: 'twitter',
    icon: <TwitterOutlined />,
    input: 'Tweet content and user data',
    output: 'Twitter operation result',
    data: {
      type: 'twitter',
      form: {
        role: 'developer',
        name: 'Twitter',
        description: 'Interact with Twitter for social media management',
        action: 'create_tweet',
        apiKey: '',
        apiSecret: '',
        accessToken: '',
        accessTokenSecret: '',
        tweetText: '{{tweetContent}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<TwitterNodeData>,
  },
  instagram: {
    type: 'instagram',
    icon: <InstagramOutlined />,
    input: 'Media content and captions',
    output: 'Instagram operation result',
    data: {
      type: 'instagram',
      form: {
        role: 'developer',
        name: 'Instagram',
        description: 'Interact with Instagram for content management',
        action: 'create_post',
        accessToken: '',
        caption: '{{postCaption}}',
        mediaType: 'image',
        inputRefs: [],
        output: '',
      },
    } as Partial<InstagramNodeData>,
  },
  linkedin: {
    type: 'linkedin',
    icon: <LinkedinOutlined />,
    input: 'Professional content and connections',
    output: 'LinkedIn operation result',
    data: {
      type: 'linkedin',
      form: {
        role: 'developer',
        name: 'LinkedIn',
        description: 'Interact with LinkedIn for professional networking',
        action: 'create_post',
        accessToken: '',
        postText: '{{linkedinPost}}',
        visibility: 'public',
        inputRefs: [],
        output: '',
      },
    } as Partial<LinkedInNodeData>,
  },
  youtube: {
    type: 'youtube',
    icon: <YoutubeOutlined />,
    input: 'Video content and metadata',
    output: 'YouTube operation result',
    data: {
      type: 'youtube',
      form: {
        role: 'developer',
        name: 'YouTube',
        description: 'Interact with YouTube for video management',
        action: 'get_videos',
        apiKey: '',
        title: '{{videoTitle}}',
        videoDescription: '{{videoDescription}}',
        privacy: 'public',
        inputRefs: [],
        output: '',
      },
    } as Partial<YouTubeNodeData>,
  },
  tiktok: {
    type: 'tiktok',
    icon: <CustomerServiceOutlined />,
    input: 'Video content and hashtags',
    output: 'TikTok operation result',
    data: {
      type: 'tiktok',
      form: {
        role: 'developer',
        name: 'TikTok',
        description: 'Interact with TikTok for short video content',
        action: 'get_user_info',
        accessToken: '',
        caption: '{{tikTokCaption}}',
        privacy: 'public',
        inputRefs: [],
        output: '',
      },
    } as Partial<TikTokNodeData>,
  },
  discord: {
    type: 'discord',
    icon: <DiscordIcon />,
    input: 'Messages and server data',
    output: 'Discord operation result',
    data: {
      type: 'discord',
      form: {
        role: 'developer',
        name: 'Discord',
        description: 'Interact with Discord for community management',
        action: 'send_message',
        botToken: '',
        message: '{{discordMessage}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<DiscordNodeData>,
  },
  telegram: {
    type: 'telegram',
    icon: <PhoneOutlined />,
    input: 'Messages and media content',
    output: 'Telegram operation result',
    data: {
      type: 'telegram',
      form: {
        role: 'developer',
        name: 'Telegram',
        description: 'Interact with Telegram for messaging',
        action: 'send_message',
        botToken: '',
        message: '{{telegramMessage}}',
        parseMode: 'Markdown',
        inputRefs: [],
        output: '',
      },
    } as Partial<TelegramNodeData>,
  },
  whatsapp: {
    type: 'whatsapp',
    icon: <WhatsAppOutlined />,
    input: 'Messages and business communications',
    output: 'WhatsApp operation result',
    data: {
      type: 'whatsapp',
      form: {
        role: 'developer',
        name: 'WhatsApp',
        description: 'Interact with WhatsApp Business API',
        action: 'send_message',
        accessToken: '',
        phoneNumberId: '',
        recipientPhone: '',
        message: '{{whatsappMessage}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<WhatsAppNodeData>,
  },
  bingsearch: {
    type: 'bingsearch',
    icon: <SearchOutlined />,
    input: 'Search query text',
    output: 'Bing search results with titles, descriptions, and URLs',
    data: {
      type: 'bingsearch',
      form: {
        role: 'developer',
        name: 'Bing Search',
        description: 'Search Bing for information and return results',
        query: '{{searchTerm}}',
        maxResults: 10,
        safeSearch: 'moderate',
        language: 'en',
        country: 'us',
        searchType: 'web',
        useSystemConfig: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<BingSearchNodeData>,
  },
  duckgosearch: {
    type: 'duckgosearch',
    icon: <SearchOutlined />,
    input: 'Search query text',
    output: 'DuckDuckGo search results with titles, descriptions, and URLs',
    data: {
      type: 'duckgosearch',
      form: {
        role: 'developer',
        name: 'DuckDuckGo Search',
        description: 'Search DuckDuckGo for privacy-focused results',
        query: '{{searchTerm}}',
        maxResults: 10,
        safeSearch: 'moderate',
        region: 'us-en',
        searchType: 'web',
        noHTML: true,
        noRedirect: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<DuckGoSearchNodeData>,
  },
  weather: {
    type: 'weather',
    icon: <CloudOutlined />,
    input: 'Location name or coordinates',
    output: 'Weather data and forecast information',
    data: {
      type: 'weather',
      form: {
        role: 'developer',
        name: 'Weather',
        description: 'Get weather information and forecasts',
        action: 'current_weather',
        location: '{{location}}',
        units: 'metric',
        language: 'en',
        days: 5,
        includeHourly: false,
        includeAlerts: true,
        useSystemConfig: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<WeatherNodeData>,
  },
  display: {
    type: 'display',
    icon: <EyeOutlined />,
    input: 'Content to display from previous nodes',
    output: 'Displayed content (final output)',
    data: {
      type: 'display',
      form: {
        role: 'assistant',
        name: 'Display',
        description: 'Display output to users',
        outputFormat: 'text',
        showAsModal: false,
        content: '{{previousOutput}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<DisplayNodeData>,
  },
  loop: {
    type: 'loop',
    icon: <ReloadOutlined />,
    input: 'Array, object, or range data to iterate over',
    output: 'Iteration results and loop control',
    data: {
      type: 'loop',
      form: {
        role: 'developer',
        name: 'Loop',
        description: 'Iterate over collections or ranges',
        loopType: 'array',
        inputData: '{{arrayData}}',
        maxIterations: 100,
        currentItemVariable: 'currentItem',
        currentIndexVariable: 'currentIndex',
        stepSize: 1,
        inputRefs: [],
        output: '',
      },
    } as Partial<LoopNodeData>,
  },
  variable: {
    type: 'variable',
    icon: <SettingOutlined />,
    input: 'Variable name and value for operations',
    output: 'Variable operation result',
    data: {
      type: 'variable',
      form: {
        role: 'developer',
        name: 'Variable',
        description: 'Set, get, or manipulate variables',
        operation: 'set',
        variableName: 'myVariable',
        variableValue: '{{inputValue}}',
        defaultValue: '',
        inputRefs: [],
        output: '',
      },
    } as Partial<VariableNodeData>,
  },
  code: {
    type: 'code',
    icon: <CodeIcon />,
    input: 'Input data for JavaScript processing',
    output: 'Result of code execution',
    data: {
      type: 'code',
      form: {
        role: 'developer',
        name: 'Code',
        description: 'Execute custom JavaScript code',
        code: '// Process input data\nreturn { result: inputs.data };',
        timeout: 5000,
        allowConsole: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<CodeNodeData>,
  },
  template: {
    type: 'template',
    icon: <TemplateIcon />,
    input: 'Template variables and data',
    output: 'Rendered template content',
    data: {
      type: 'template',
      form: {
        role: 'assistant',
        name: 'Template',
        description: 'Render templates with variables',
        templateEngine: 'simple',
        templateContent: 'Hello {{name}}!\nYour status is {{status}}.',
        outputFormat: 'text',
        inputRefs: [],
        output: '',
      },
    } as Partial<TemplateNodeData>,
  },
  counter: {
    type: 'counter',
    icon: <NumberOutlined />,
    input: 'Counter operations and values',
    output: 'Current counter value',
    data: {
      type: 'counter',
      form: {
        role: 'developer',
        name: 'Counter',
        description: 'Count events and maintain numeric counters',
        counterName: 'myCounter',
        operation: 'increment',
        stepValue: 1,
        initialValue: 0,
        inputRefs: [],
        output: '',
      },
    } as Partial<CounterNodeData>,
  },
  cache: {
    type: 'cache',
    icon: <InboxOutlined />,
    input: 'Cache keys and values for storage/retrieval',
    output: 'Cached data or operation result',
    data: {
      type: 'cache',
      form: {
        role: 'developer',
        name: 'Cache',
        description: 'Store and retrieve cached data',
        operation: 'get',
        cacheKey: 'dataKey_{{userId}}',
        cacheValue: '{{dataToCache}}',
        ttl: 3600,
        defaultValue: '{}',
        inputRefs: [],
        output: '',
      },
    } as Partial<CacheNodeData>,
  },
  log: {
    type: 'log',
    icon: <FileSearchOutlined />,
    input: 'Log messages and data to record',
    output: 'Log entry confirmation',
    data: {
      type: 'log',
      form: {
        role: 'developer',
        name: 'Log',
        description: 'Log information for debugging and monitoring',
        logLevel: 'info',
        message: 'Processing {{action}} for user {{userId}}',
        includeData: '{{currentData}}',
        includeTimestamp: true,
        includeNodeInfo: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<LogNodeData>,
  },
  fileanalysis: {
    type: 'fileanalysis',
    icon: <FileSearchOutlined />,
    input: 'File paths and analysis parameters',
    output: 'File analysis results and metadata',
    data: {
      type: 'fileanalysis',
      form: {
        role: 'developer',
        name: 'File Analysis',
        description: 'Analyze files and directories for metadata, content, and structure',
        filePath: '{{filePath}}',
        analysisType: 'metadata',
        fileTypes: ['*'],
        includeHidden: false,
        recursive: false,
        outputFormat: 'json',
        inputRefs: [],
        output: '',
      },
    } as Partial<FileAnalysisNodeData>,
  },
  csvanalysis: {
    type: 'csvanalysis',
    icon: <TableOutlined />,
    input: 'CSV file path and analysis configuration',
    output: 'CSV data analysis and statistics',
    data: {
      type: 'csvanalysis',
      form: {
        role: 'developer',
        name: 'CSV Analysis',
        description: 'Analyze CSV files for data quality, statistics, and insights',
        filePath: '{{csvFile}}',
        operation: 'analyze',
        delimiter: ',',
        hasHeader: true,
        encoding: 'utf8',
        inputRefs: [],
        output: '',
      },
    } as Partial<CsvAnalysisNodeData>,
  },
  imageanalysis: {
    type: 'imageanalysis',
    icon: <PictureOutlined />,
    input: 'Image file path and analysis type',
    output: 'Image metadata, dimensions, colors, or OCR text',
    data: {
      type: 'imageanalysis',
      form: {
        role: 'developer',
        name: 'Image Analysis',
        description: 'Analyze images for metadata, OCR, colors, and object detection',
        imagePath: '{{imagePath}}',
        analysisType: 'metadata',
        ocrLanguage: 'eng',
        colorPalette: 5,
        outputDetails: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<ImageAnalysisNodeData>,
  },
  pdfanalysis: {
    type: 'pdfanalysis',
    icon: <FilePdfOutlined />,
    input: 'PDF file path and extraction parameters',
    output: 'Extracted text, metadata, or split PDF files',
    data: {
      type: 'pdfanalysis',
      form: {
        role: 'developer',
        name: 'PDF Analysis',
        description: 'Extract text, metadata, and images from PDF files',
        pdfPath: '{{pdfPath}}',
        operation: 'extract_text',
        preserveFormatting: true,
        extractImages: false,
        inputRefs: [],
        output: '',
      },
    } as Partial<PdfAnalysisNodeData>,
  },
  loganalysis: {
    type: 'loganalysis',
    icon: <BugOutlined />,
    input: 'Log file path and analysis configuration',
    output: 'Log analysis summary, errors, and trends',
    data: {
      type: 'loganalysis',
      form: {
        role: 'developer',
        name: 'Log Analysis',
        description: 'Analyze log files for errors, performance, and security issues',
        logPath: '{{logPath}}',
        logFormat: 'apache',
        analysisType: 'summary',
        filterLevel: 'info',
        groupBy: 'hour',
        inputRefs: [],
        output: '',
      },
    } as Partial<LogAnalysisNodeData>,
  },
  excelanalysis: {
    type: 'excelanalysis',
    icon: <FileExcelOutlined />,
    input: 'Excel file path and sheet configuration',
    output: 'Excel data, formulas, and analysis results',
    data: {
      type: 'excelanalysis',
      form: {
        role: 'developer',
        name: 'Excel Analysis',
        description: 'Analyze Excel files for data, formulas, and pivot tables',
        filePath: '{{excelPath}}',
        operation: 'read_sheets',
        includeFormulas: false,
        skipEmptyRows: true,
        inputRefs: [],
        output: '',
      },
    } as Partial<ExcelAnalysisNodeData>,
  },

  // WeChat node
  wechat: {
    type: 'wechat',
    icon: <WechatOutlined />,
    input: 'WeChat API credentials and message content',
    output: 'WeChat operation result',
    data: {
      type: 'wechat',
      form: {
        role: 'developer',
        name: 'WeChat',
        description: 'Interact with WeChat Official Account and Mini Program APIs',
        action: 'send_message',
        appId: '',
        appSecret: '',
        message: '{{wechatMessage}}',
        inputRefs: [],
        output: '',
      },
    } as Partial<WeChatNodeData>,
  },
};

// Get available input sources for the query - specifically for nodes that support input references
export function getQueryInputSources(): Array<{ id: string; name: string; description: string }> {
  return [
    {
      id: 'user_input',
      name: 'User Input',
      description: 'The most recent input from the user',
    },
    {
      id: 'generated_text',
      name: 'Generated Text',
      description: 'Output from the most recent Generate node',
    },
    {
      id: 'retrieval_results',
      name: 'Retrieval Results',
      description: 'Results from the most recent Retrieval node',
    },
  ];
}

// Get input/output info for a node type
export function getNodeInputInfo(nodeType: NodeTypeString) {
  return NODE_REGISTRY[nodeType]?.input ?? undefined;
}
