name: NodeJS with Webpack

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened, labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci')

    strategy:
      matrix:
        node-version: [19.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Clear Next.js Cache
        run: rm -rf .next

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run lint
          npm run build

      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
          
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "🚨 CI/CD Build Failed"
          content-filepath: .github/ISSUE_TEMPLATE/build_failed.md
          labels: bug, ci